import React from 'react';
import { makeStyles } from '@material-ui/core/styles';
import { HorizontalBar } from 'react-chartjs-2';
import 'chartjs-plugin-datalabels';

const useStyles = makeStyles({
    root: {
        width: "30vw",
        background: "white",
        borderRadius: "20px"
    },
    title: {
        paddingTop: "5px",
        fontSize: "2vw",
        fontWeight: "normal"
    },
    line: {
        width: "90%"
    },
    statsContainer: {
        textAlign: "left",
        marginLeft: "5%"
    },
    stats: {
        fontSize: "1.2vw"
    },
    directionBtn: {
        padding: "0.8vw",
        fontSize: "1.1vw",
        borderRadius: "0.8vw",
        border: "none",
        outline: "none",
        color: "white",
        background: "#04034E",
        '&:hover': {
            cursor: "pointer",
            transition: "transform 0.3s ease-out",
            transform: "scale(0.97)"
        },
    },
    offsetBtn: {
        padding: "0.8vw 1.5vw 0.8vw 1.5vw",
        marginBottom: "1vw",
        fontSize: "1.5vw",
        borderRadius: "1vw",
        border: "none",
        outline: "none",
        color: "white",
        background: "#84C58B",
        '&:hover': {
            cursor: "pointer",
            transition: "transform 0.3s ease-out",
            transform: "scale(0.97)"
        },
    },
    callToAction: {
        fontSize: "1vw",
        fontWeight: "normal",
        marginTop: "0",
        paddingLeft: "5%",
        paddingRight: "5%",
    }
});

const options = {
    responsive: true,
    maintainAspectRatio: true,
    layout: {
        padding: {
            top: 10,
            left: 20,
            right: 40,
            bottom: 10
        }
    },
    legend: {
        display: false
    },
    scales: {
        xAxes: [{
            gridLines: {
                display:false
            },
            ticks: {
                display: false
            }
        }],
        yAxes: [{
            categoryPercentage: 1,
            barPercentage: 0.3,
            gridLines: {
                display:false
            },
            ticks: {
                mirror: true,
                labelOffset: -18,
            }
        }]
    },
    plugins: {
        datalabels: {
           display: true,
           align: 'right',
           anchor: 'end'
        }
    }
}

const TripReport = () => {
    const classes = useStyles();
    const data = {
        labels: ['Your Trip', 'Max annual CO2 per person', 'Average monthly CO2 generated by an individual'],
        datasets: [
          {
            label: 'CO2 emission (ton)',
            backgroundColor: ["#84C58B", "#04034E", "#04034E"],
            borderWidth: 1,
            data: [0.04, 0.6, 1.375]
          }
        ]
    };
    return (
        <div className={classes.root}>
            <h1 className={classes.title}>Your Trip Report</h1>
            <hr className={classes.line} />
            <div className={classes.statsContainer}>
                <h3 className={classes.stats}>Distance: </h3>
                <h3 className={classes.stats}>Time: </h3>
                <h3 className={classes.stats}>CO2 Emission: </h3>
            </div>
            <button className={classes.directionBtn} > Get Directions </button>
            <HorizontalBar data={data} options={options} height="90vh" paddingTop="10px"/>
            <p className={classes.callToAction}>Help save the planet by choosing eco-friendly transport modes or offsetting your carbon footprint</p>
            <button className={classes.offsetBtn} > Offset </button>
        </div>
    )
}

export default TripReport;