name: 'deploy'
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Deploy to Heroku
        id: heroku
        uses: snithyanantham/docker-compose-multiple-apps-heroku-deploy@v1.0
        with:
          email: ${{ secrets.HEROKU_EMAIL }} 
          api_key: ${{ secrets.HEROKU_API_KEY }} 
          docker_compose_file: './docker-compose.yml'
          heroku_apps: '[{"imagename":"vehico_server","appname":"vehico-server","apptype":"web"},{"imagename":"vehico_client","appname":"vehico-client","apptype":"web"}]'
